### PR TITLE
Enhancement/default types

### LINKED ISSUE #467: Select only forager and freegan types by default
To match user expectations and the behavior of the current interfaces, the new `categories` property of each location type should be used to initialise the type tree filter with just those types selected.

### PR DESCRIPTION
**Pull request by frankgomezdev**
Closes #467. After implementing the changes, I used the data response from the browser's network tab to verify that the default selected options include 'forager' or 'freegan' as categories using the find function. Unfortunately, I did not check all of them.

Let me know if you'd like further adjustments!

image

### CODE REVIEW

**Comment by wbazant** [comment]
@frankgomezdev Thanks! I've not ran the code yet, but from looking at the implementation, there seems to be bug for a filter indicator: if we uncheck Apple (forager category) but select Oak (not forager or freegan) we'll have non-default selection which misses a filter indicator because it's of the same length. Could you compare as sets?

**Comment by wbazant** [comment]
Thanks @ezwelty  for making the issue and @frankgomezdev for doing this work! I knew about us needing the categories for the beta release, had vague ideas, and wasn't doing anything with them.

 @frankgomezdev if you'd like to do more work on the categories epic, I think the next step here is implementing them with a simple UI. I wrote up a plan in https://github.com/falling-fruit/falling-fruit-web/issues/383#issuecomment-2404655012  and can try to help you on the way, and you're also welcome to grab any other issue.

**Comment by frankgomezdev** [comment]
That sounds good! I just took a peek, and steps 1 and 2 seem pretty manageable, but I might need some help with 3 and 4.

**Comment by wbazant** [comment]
@frankgomezdev All right, we can try that! If you get stuck on the way, you can open a draft pull request.

There's also a non-implementation related difficulty to this task, we're not super sure how the UI should work - see the discussion - especially what the categories should do to the type tree - are they like search filters, or like the Select all / Deselect all button - but we can figure them out on the way.

**Pull request merged**
