### PR TITLE
feat(#607): Changed outdated Twitter icon on share page

### PR DESCRIPTION
**Pull request by ahmedhalac**
Related to #607

### CODE REVIEW

**Comment by ahmedhalac** [comment]
Testing result:

Screenshot 2024-11-22 at 1 20 08 AM

**Comment by ezwelty** [comment]
@ahmedhalac Thanks for taking this on! Upon review, I realized that there were some other related issues with the code base (e.g. missing instagram icons, misuse of entry `RESOURCES` which is meant for location type rendering) and decided to build on what you'd started to address those as well. I also think the table looks nicer if we simple reuse the same icons that we use in the top bar. Do you agree?

**Comment by ahmedhalac** [comment]
> @ahmedhalac Thanks for taking this on! Upon review, I realized that there were some other related issues with the code base (e.g. missing instagram icons, misuse of entry `RESOURCES` which is meant for location type rendering) and decided to build on what you'd started to address those as well. I also think the table looks nicer if we simple reuse the same icons that we use in the top bar. Do you agree?
> 
> 
> 
> 

Okay, I will check and get back to you with testing results.

**Comment by ahmedhalac** [comment]
Hi @ezwelty. It looks much more cleaner now. Social icons in the table are matching navbar icons which is far better.

**Comment by ezwelty** [comment]
> Do you need any changes from me here?

@ahmedhalac Nope, just merged. Thanks again!

**Pull request merged**
